version: '3'

services:
  webapp:
    container_name: webapp
    build: ../client
    ports:
      - 80:80
  # server:
  #   container_name: server
  #   build:
  #     context: ./server
  #   ports:
  #     - 3000:3000
